osx_image: xcode10.1
language: swift
xcode_workspace: mosque-gazeteer.xcworkspace

xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone XR

before_install:
  - gem install -v 2.0.2 bundler --no-rdoc --no-ri
  - bundle _2.0.2_ install

script:
  - bundle exec fastlane pr_build

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'mosque-gazeteer'